### PR TITLE
Adding UKB notebook

### PR DESCRIPTION
**Pull request by chaimaafadil**
Here's the notebook for figure 5. Can you please check it out and let me know if you have any comments! I might submit a more up-to-date version in the next 2 days.

### CODE REVIEW

**Comment by chaimaafadil** [comment]
1. I've added an updated version of the notebook with minor changes to the section numbering, markdown and typo corrections. Let me know if you have any comments on the title or summary at the start.
2. I added 2 CSV files that are used as input in the notebook. It might be better to have the notebook and these 2 files in a separate folder.
3. I update the last part of the README to refer to the notebook.

**Comment by jeromekelleher** [comment]
Loogs good to me, thanks @chaimaafadil. @hyanwong, can you look over this and merge please if you're happy with it? (gitHubbing is increasingly challenging on my laptop!)

**Comment by hyanwong** [comment]
OK, will check. Apologies about the slow response, currently on holiday in Dublin, so grabbing time here and there to tick off TO DOs.

**Comment by jeromekelleher** [comment]
Thanks @hyanwong, no hurry until you get back. Enjoy Dublin!

**Comment by hyanwong** [comment]
Looks great, and very comprehensive. Thanks @chaimaafadil. I've made a few grammatical changes in https://github.com/chaimaafadil/treeseq-inference/pull/1. A couple of extra things, however: 

1) it would be sensible to add the DOI for the paper when we first mention the title of the publication. I don't know if we've been given a DOI yet, however.
2) We mention the augmented samples but don't explain anything about this. I'm not sure if we should have a few sentences of explanation or not?

Happy to merge when I get back.

**Comment by chaimaafadil** [comment]
Thanks for the corrections @hyanwong.
1. That's a good idea. I don't know that we have a DOI as of now but I'm happy to add it once we do.
2. That could go in the paragraph for 'Section 2' in the intro. Do you or @jeromekelleher  have any suggestions on how to formulate that in a succinct way?

**Comment by jeromekelleher** [comment]
We have been assigned a DOI: 10.1038/s41588-019-0483-y

Perhaps something like:  "Augmented samples are those that were sequentially added to the ancestors tree sequence so that path compression could generate additional ancestors through signals of shared recombination breakpoints. To avoid biasing the analysis, we remove these samples from our analysis"

**Comment by chaimaafadil** [comment]
Thanks @jeromekelleher. I updated the notebook with the DOI and added a few sentences at the start of '2. Compute GNN matrix' to explain the augmented samples. Let me know if you have any other comments before merging @hyanwong.

**Comment by hyanwong** [comment]
LGTM. Shall I merge, or does someone else want to?

**Comment by jeromekelleher** [comment]
Go for it.

**Comment by awohns** [comment]
@chaimaafadil the file ukb_metadata.csv is not in the human-data directory so cell 1.1 'Input files' in your notebook breaks

**Pull request merged**
