### PR TITLE
Backup kc calc

### PR DESCRIPTION
**Pull request by hyanwong**
This should remove the need for installing masses of R packages.

Users can install in one of 2 ways:

1. From within R, as long as they have the `devtools` package installed. Do `library(devtools); install("ARGmetrics");` from an R prompt within the treeseq-inference directory. This should install all the necessary dependencies (ape, phangorn, Rcpp, etc) from CRAN.

2. From the (e.g. bash) command-line,  assuming that users have already installed `ape`, `phangorn`, and `Rcpp` in their local version of R. Then they can run `R CMD INSTALL path/to/ARGmetrics` on the unix command-line, without having to enter R at all.

I think 2. is the easiest to automate. Can you check it works with your auto-installation, before accepting this PR?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This is still causing problems on my installation. Do we really need ape >= 4.1? Looks like the version on Ubuntu is < than this, so we have to compile it as well. When I try to compile it I get missing library errors.

I'm not really sure what we're gaining here: we still need ape and phangorn. 

Ah, I see, it's treespace that's the real culprit here:
```
jk@powderfinger$ sudo apt-get install r-cran-treespace
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-42 linux-headers-4.15.0-42-generic linux-image-4.15.0-42-generic
  linux-modules-4.15.0-42-generic linux-modules-extra-4.15.0-42-generic python-singledispatch
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  r-cran-ade4 r-cran-adegenet r-cran-adegraphics r-cran-adephylo r-cran-animation r-cran-assertthat r-cran-bbmle
  r-cran-bindr r-cran-bindrcpp r-cran-bitops r-cran-bold r-cran-boot r-cran-catools r-cran-cellranger r-cran-cli
  r-cran-cluster r-cran-clustergeneration r-cran-coda r-cran-codetools r-cran-colorspace r-cran-combinat
  r-cran-crayon r-cran-crul r-cran-data.table r-cran-deldir r-cran-dichromat r-cran-distory r-cran-dotcall64
  r-cran-dplyr r-cran-ellipse r-cran-expm r-cran-fields r-cran-foreach r-cran-gdata r-cran-ggplot2 r-cran-glue
  r-cran-gmodels r-cran-googlevis r-cran-gplots r-cran-gtable r-cran-gtools r-cran-htmltools r-cran-htmlwidgets
  r-cran-httpcode r-cran-httpuv r-cran-iterators r-cran-kernsmooth r-cran-labeling r-cran-latticeextra
  r-cran-lazyeval r-cran-learnbayes r-cran-luminescence r-cran-maps r-cran-mass r-cran-matrixstats r-cran-mgcv
  r-cran-minpack.lm r-cran-mnormt r-cran-msm r-cran-munsell r-cran-mvtnorm r-cran-natserv r-cran-numderiv
  r-cran-phylobase r-cran-phytools r-cran-pillar r-cran-plotrix r-cran-plyr r-cran-prettyunits r-cran-progress
  r-cran-purrr r-cran-raster r-cran-rcolorbrewer r-cran-readxl r-cran-rematch r-cran-rentrez r-cran-reshape
  r-cran-reshape2 r-cran-rhandsontable r-cran-ritis r-cran-rlang r-cran-rlumshiny r-cran-rncl r-cran-rnexml
  r-cran-rotl r-cran-rredlist r-cran-scales r-cran-scatterd3 r-cran-scatterplot3d r-cran-segmented r-cran-seqinr
  r-cran-shape r-cran-shiny r-cran-shinybs r-cran-shinydashboard r-cran-solrium r-cran-sourcetools r-cran-sp
  r-cran-spam r-cran-spdep r-cran-stringi r-cran-stringr r-cran-survival r-cran-taxize r-cran-tibble r-cran-tidyr
  r-cran-tidyselect r-cran-triebeard r-cran-urltools r-cran-utf8 r-cran-uuid r-cran-vegan r-cran-viridislite
  r-cran-wikidatar r-cran-wikipedir r-cran-wikitaxa r-cran-worrms r-cran-xml r-cran-xml2 r-cran-xtable r-cran-yaml
  r-cran-zoo
Suggested packages:
  r-cran-testthat r-cran-guerry r-cran-knitr r-cran-class r-cran-testit r-cran-rms r-cran-runit r-cran-hmisc
  r-cran-rpart r-cran-mockery r-cran-kernlab r-cran-vcd r-cran-shinyjs r-cran-webmockr r-cran-bit64 r-cran-chron
  r-cran-hexbin r-cran-xts r-bioc-genomicranges r-cran-caret r-cran-polyclip r-cran-dbplyr r-cran-dbi r-cran-hms
  r-cran-rmysql r-cran-rpostgresql r-cran-rsqlite r-cran-mapproj r-cran-multcomp r-cran-quantreg r-cran-r.utils
  r-cran-forcats r-cran-markdown r-cran-rjags r-cran-mapdata r-cran-base64enc r-cran-minqa r-cran-doparallel
  r-cran-rgl r-cran-abind r-cran-ncdf4 r-cran-miniui r-cran-cairo r-cran-sparsem r-cran-truncdist r-cran-foreign
  r-cran-lsmeans
The following NEW packages will be installed
  r-cran-ade4 r-cran-adegenet r-cran-adegraphics r-cran-adephylo r-cran-animation r-cran-assertthat r-cran-bbmle
  r-cran-bindr r-cran-bindrcpp r-cran-bitops r-cran-bold r-cran-boot r-cran-catools r-cran-cellranger r-cran-cli
  r-cran-cluster r-cran-clustergeneration r-cran-coda r-cran-codetools r-cran-colorspace r-cran-combinat
  r-cran-crayon r-cran-crul r-cran-data.table r-cran-deldir r-cran-dichromat r-cran-distory r-cran-dotcall64
  r-cran-dplyr r-cran-ellipse r-cran-expm r-cran-fields r-cran-foreach r-cran-gdata r-cran-ggplot2 r-cran-glue
  r-cran-gmodels r-cran-googlevis r-cran-gplots r-cran-gtable r-cran-gtools r-cran-htmltools r-cran-htmlwidgets
  r-cran-httpcode r-cran-httpuv r-cran-iterators r-cran-kernsmooth r-cran-labeling r-cran-latticeextra
  r-cran-lazyeval r-cran-learnbayes r-cran-luminescence r-cran-maps r-cran-mass r-cran-matrixstats r-cran-mgcv
  r-cran-minpack.lm r-cran-mnormt r-cran-msm r-cran-munsell r-cran-mvtnorm r-cran-natserv r-cran-numderiv
  r-cran-phylobase r-cran-phytools r-cran-pillar r-cran-plotrix r-cran-plyr r-cran-prettyunits r-cran-progress
  r-cran-purrr r-cran-raster r-cran-rcolorbrewer r-cran-readxl r-cran-rematch r-cran-rentrez r-cran-reshape
  r-cran-reshape2 r-cran-rhandsontable r-cran-ritis r-cran-rlang r-cran-rlumshiny r-cran-rncl r-cran-rnexml
  r-cran-rotl r-cran-rredlist r-cran-scales r-cran-scatterd3 r-cran-scatterplot3d r-cran-segmented r-cran-seqinr
  r-cran-shape r-cran-shiny r-cran-shinybs r-cran-shinydashboard r-cran-solrium r-cran-sourcetools r-cran-sp
  r-cran-spam r-cran-spdep r-cran-stringi r-cran-stringr r-cran-survival r-cran-taxize r-cran-tibble r-cran-tidyr
  r-cran-tidyselect r-cran-treespace r-cran-triebeard r-cran-urltools r-cran-utf8 r-cran-uuid r-cran-vegan
  r-cran-viridislite r-cran-wikidatar r-cran-wikipedir r-cran-wikitaxa r-cran-worrms r-cran-xml r-cran-xml2
  r-cran-xtable r-cran-yaml r-cran-zoo
```

I think we need to just give instructions for how to make this work on  a clean Ubuntu machine. It's pulling in a huge amount of code whatever way you do it, so we just have to give some instructions that'll work.

**Comment by hyanwong** [comment]
It needs ape >= 4.1 for a bug in ape that I corrected. But it shouldn't pull in treespace, although I haven't tested on ubuntu. I'll try on Holly now.

**Comment by hyanwong** [comment]
@jeromekelleher I just removed all my locally installed packages in R on holly, then reinstalled ape and phangorn from within R using

```
install.packages(c("ape","phangorn","Rcpp"))
```

which admittedly took about 3 mins to compile and install graph (nothing we can do about that).

Then I went to the `treeseq-inference` directory and typed:

```
R CMD INSTALL ARGmetrics
```

which installed with no fuss in about 3 seconds. You can tell it works by

```
$ python3 ./src/ARG_metrics.py 
$ python3 ./src/ARG_metrics.py 
{'RFunrooted': 0.0, 'KCrooted': 1.0606601717798214, 'wRFunrooted': nan, 'wRFrooted': nan, 'pathunrooted': 0.0, 'RFrooted': 1.5, 'SPRunrooted': 0.0}
{'RFunrooted': 0.0, 'KCrooted': 0.565685424949238, 'wRFunrooted': nan, 'wRFrooted': nan, 'pathunrooted': 0.0, 'RFrooted': 0.8, 'SPRunrooted': 0.0}

```

**Comment by hyanwong** [comment]
p.s. we shouldn't *need* to install treespace now, so I'm not sure why you are doing `sudo apt-get install r-cran-treespace`?

**Comment by jeromekelleher** [comment]
> p.s. we shouldn't need to install treespace now, so I'm not sure why you are doing sudo apt-get install r-cran-treespace?

You're right, we don't. I was just confirming how many packages treespace pulls in and that it was a good move to pull it out.

> @jeromekelleher I just removed all my locally installed packages in R on holly, then reinstalled ape and phangorn from within R using

All the system libraries needed are already installed on holly though. You'd need to do this on a clean Ubuntu system to be able to give proper instructions. Can you make VMs on your laptop? I can spin on up on holly if that's easier.

Anyway, that's documentation, which we also need. I'm happy to merge this much now, so go ahead whenever you like.

**Comment by hyanwong** [comment]
Thanks for confirming. I don't have much space on my laptop, so would prefer to spin up a VM on holly if possible. Could you tell me how?!

I'll merge now too.

**Pull request merged**
