### PR TITLE
parent gnn changed to local gnn; figure 4d plot code updated

### PR DESCRIPTION
**Pull request by awohns**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM! Can you delete the ".Dsstore files" left around though please?

**Comment by awohns** [comment]
Ok, I think I got all of them

**Comment by jeromekelleher** [comment]
Ah, you need to add the new CSVs and delete the old ones also.

**Comment by awohns** [comment]
Got it. The new csv’s are dramatically bigger. It’ll take a few pretty trivial lines to make them dramatically smaller, I’ll do this tomorrow morning.

**Comment by jeromekelleher** [comment]
OK yeah, these are huge. Shrinking them down a bit would be good.

**Comment by awohns** [comment]
Pushed the smaller CSVs and revised code

**Comment by jeromekelleher** [comment]
Great, thank @awohns! I squashed down some commits to clean up the history, so your fork's master branch will now be out of sync, FYI.

**Pull request merged**
